server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 123456
    #使用的druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      maxActive: 20
      maxWait: 60000
      minIdle: 1
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      time-between-eviction-runs-millis: 60000
    name: blog
  #Redis配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 1000
        min-idle: 1
        max-idle: 100
        max-wait: -1ms
  #RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test123
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 2 #最小消息监听线程数
        max-concurrency: 2 #最大消息监听线程数
mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml